config/routes.rb
Rails.application.routes.draw do  

  resources :vendors

  devise_for :users
  resources :movies do
    collection do
      get 'search' => 'movies#search'
    end
    resources :reviews, except: [:show, :index]
  end
  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  mount_uploader :image, ImageUploader
  validates_presence_of :title, :description
  searchkick
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies   
  has_many :reviews , dependent: :destroy   
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_image

  def crop_image
    image.recreate_versions! if crop_x.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    @movies = Movie.all
    if params[:search].present?
      #@movie = Movie.search(params[:search])
    else
      #@movie = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :user_id, :image,:movie_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user! 

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
    if @review.save
      redirect_to @movie
    else
      render 'new'
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path 
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendor.all
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def new
    @vendor = Vendor.new
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      if params[:vendor][:image].present?
        render 'crop'
      else
        redirect_to @vendor, notice: "Successfully created vendor"
      end
    else
      render 'new'
    end
  end

  def update

    if @vendor.update(vendor_params)
      if params[:vendor][:image].present?
        render 'crop'
      else
        redirect_to @vendor, notice: "Successfully updated user."
      end
    else
      render 'edit'
    end

  end


  def destroy
    @vendor.destroy
    redirect_to vendors_url
  end

  private
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def vendor_params
      params.require(:vendor).permit(:name, :image, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/_nav.html.erb
	<nav class="navbar navbar-default" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Movie's Blog", root_path ,:class => "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class=""><a href="#">About us</a><span class="sr-only">(current)</span></li>
                <li><a href="#">Contact us</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>

              <%= form_tag search_movies_path, method: :get , class: "navbar-form navbar-left", role: "search" do %>
                <div class="form-group">
                    <%= text_field_tag :search, params['search'], class: "form-control" %>
                </div>
                <%= submit_tag "Search" , name: nil, class: "btn btn-default" %>
              <% end %>
              <!--
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
              </form>
              -->
              <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li><%= link_to "Add Movie", new_movie_path  %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                    <li><%= link_to "Login", new_user_session_path  %></li>
                    <li><%= link_to "Signup", new_user_registration_path  %></li>
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Review</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>	
<div class='container'>	
<% flash.each do |name, msg|%>
	<%= content_tag(:div, msg, class: "alert alert-info")%>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :movie_length %><br>
    <%= f.text_field :movie_length %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="row">
	<% @movies.each do |movie| %>
	<div class="col-sm-6 col-md-3">
		<div class="thumbnail">
			<%= link_to (image_tag movie.image , class: "image", width: "100%"), movie %>
		</div>
	</div>	
	<% end %>
</div>

<%= link_to 'New Movie', new_movie_path, class: "btn btn-primary" %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to (image_tag movie.image , class: "image", width: "100%"), movie %>
        </div>
      </div>
  <% end %>
</div>

<%= link_to 'New Movie', new_movie_path, class: "btn btn-primary" %>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-sm-12 col-md-4 col-lg-6">
			  <%= image_tag @movie.image, width: "100%" %>
              <div class="star-rating" data-score=<%= @avg_review %>></div>
              <em><%= "#{@reviews.length} reviews" %></em>
              <p>
                <strong>Title:</strong>
                <%= @movie.title %>
              </p>
              <p>
                <strong>Description:</strong>
                <%= @movie.description %>
              </p>

              <p>
                <strong>Movie length:</strong>
                <%= @movie.movie_length %>
              </p>

              <p>
                <strong>Director:</strong>
                <%= @movie.director %>
              </p>

              <p>
                <strong>Rating:</strong>
                <%= @movie.rating %>
              </p>
              <p><%= link_to 'Add Review to Movie', new_movie_review_path(@movie) %></p>
			</div>
			<div class="col-sm-12 col-md-6  col-lg-6">
                <h1><%= @movie.title %></h1>
                <p><%= @movie.description %></p>

              <% if @reviews.blank? %>
                <h3>No reviews just yer, would you like to add the first!</h3>
                <p><%= link_to 'Add Review', new_movie_review_path(@movie), class: "btn btn-danger" %></p>
              <% else %>
                <% @reviews.each do |review| %>
                  <div class="reviews">
                    <div class="star-rating" data-score=<%= review.rating %>></div>
                    <p><%= review.comment %></p>
                  </div>
                <% end %>
              <% end %>
              <% #render "reviews/form"%>
			</div>
		</div>
	</div>
</div>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<script>
$('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function(){
        return $(this).attr('data-score')
    }
});
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
      path: '/assets/',
      scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/crop.html.erb
<h1>Crop Avatar</h1>

<%= image_tag @vendor.image_url(:large), id: "cropbox" %>

<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @vendor.image.url(:large), :id => "preview" %>
</div>

<%= form_for @vendor do |f| %>
    <% %w[x y w h].each do |attribute| %>
        <%= f.text_field "crop_#{attribute}" %>
    <% end %>
    <div class="actions">
      <%= f.submit "Crop" %>
    </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Listing vendors</h1>


    <% @vendors.each do |vendor| %>

        <h2><%= vendor.name %></h2>
        <%= image_tag vendor.image_url(:thumb) %>
        <p><%= link_to 'Show', vendor %>
        <%= link_to 'Edit', edit_vendor_path(vendor) %>
        <%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></p>

    <% end %>


<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <%= image_tag @vendor.image_url(:thumb) %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>